aklc/aklc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('monitor.urls')),
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]

aklc/monitor/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views, accounts, apiviews

app_name = "monitor"
urlpatterns = [
    path("", views.index, name="index"),
    path("index_gw/", views.index_gw, name="index_gw"),
    path("node/<int:node_ref>/", views.nodeDetail, name="nodeDetail"),
    path("gateway/<int:gateway_ref>/", views.gatewayDetail, name="gatewayDetail"),
    path("node/update/<int:node_ref>/", views.nodeUpdate, name="nodeUpdate"),
    path("node/modupdate/<int:node_ref>/", views.nodeModNotify, name="nodeModNotify"),
    path(
        "node/modupdateothers/<int:node_ref>/",
        views.nodeModNotifyOthers,
        name="nodeModNotifyOthers",
    ),
    path("node/remove/<int:node_ref>/", views.nodeRemove, name="nodeRemove"),
    path(
        "node/mqttlog/<int:node_ref>/<int:mq_ref>/",
        views.nodeMqttLog,
        name="nodeMqttLog",
    ),
    path(
        "gateway/mqttlog/<int:gateway_ref>/<int:mq_ref>/",
        views.gatewayMqttLog,
        name="gatewayMqttLog",
    ),
    path("node/tb1/<int:node_ref>/", views.tb1, name="tb1"),
    path("node/tb2/<int:node_ref>/", views.tb2, name="tb2"),
    path("index_msg/", views.index_msg, name="index_msg"),
    path("message/<int:msg_ref>/", views.msgDetail, name="msgDetail"),
    path("message/add/", views.msgAdd, name="msgAdd"),
    path("message/update/<int:msg_ref>/", views.msgUpdate, name="msgUpdate"),
    path("node/msgupdate/<int:node_ref>/", views.nodeMsgUpdate, name="nodeMsgUpdate"),
    path("index_prj/", views.index_prj, name="index_prj"),
    path("project/<int:prj_ref>/", views.projectDetail, name="projectDetail"),
    path("project/update/<int:prj_ref>/", views.projectUpdate, name="projectUpdate"),
    path("project/add/", views.projectAdd, name="projectAdd"),
    path("NetworkStatus/", views.dashBoard, name="DashboardStatus"),
    path("index_rp/", views.index_rp, name="index_rp"),
    path("repeater/<int:rp_ref>/", views.repeaterDetail, name="repeaterDetail"),
    path("repeater/update/<int:rp_ref>/", views.repeaterUpdate, name="repeaterUpdate"),
    path("login/", views.login, name="login"),
    path("logout/", accounts.logout, name="logout"),
    path("userprofile/", views.userProfile, name="userProfile"),
    path("userupdate/", views.userUpdate, name="userUpdate"),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url="password-change-done",
        ),
        name="passwordChange",
    ),
    path(
        "password-change/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html",
        ),
        name="passwordChangeDone",
    ),
    path("password-reset/", views.passwordReset, name="password-reset"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),

    # paths for API's
    path("api/teams/", apiviews.team_list, name="api-team-list"),
    path("api/teamdetail/<int:team_ref>/", apiviews.api_team_view, name="api-team-view"),
    path("api/nodedetail/<int:node_ref>/", apiviews.api_node_view, name="api-node-view"),
    path("api/messagelist/", apiviews.message_list, name="api-message-list"),
    path("api/messagedetail/<int:msgtype_ref>/", apiviews.message_detail, name="api-message-detail"),
]

aklc/monitor/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
from django.utils import timezone
from django import template
import json
import numbers
import html2text
from datetime import time

from monitor.utils import testPr, DEBUG, INFO, WARNING, ERROR, CRITICAL

# Create your models here.
class Team(models.Model):
    """
    Model for a Team, usually referred to as a Project by the IoT team.
    """

    teamID = models.CharField(max_length=50)
    descr = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ["teamID"]
        # verbose_name = "Project"

    def __str__(self):
        return self.teamID


class MessageType(models.Model):
    """
    Model to define different CSV message types.

    The message type consists of this header model and a number of MessageItem
    elements which need to be ordered as in the incoming payload.
    """

    msgName = models.CharField(max_length=30)
    descr = models.TextField(blank=True, null=True, help_text="")

    class Meta:
        ordering = ["msgName"]
        verbose_name = "Message Type"

    def __str__(self):
        return self.msgName


class MessageItem(models.Model):
    """
    Model for message items which are part of the MessageType element.
    """

    FIELD_TYPE_CHOICES = [
        ("S", "String"),
        ("I", "Integer"),
        ("F", "Float"),
    ]
    msgID = models.ForeignKey(
        MessageType, related_name="items", on_delete=models.CASCADE
    )
    name = models.CharField(
        max_length=15, help_text="The element name, will be used in JSON messages"
    )
    order = models.IntegerField()
    fieldType = models.CharField(
        max_length=1,
        help_text="Field type can be 'S': string, 'I': integer, 'F': float",
        choices=FIELD_TYPE_CHOICES,
    )
    isTag = models.BooleanField(
        blank=True,
        default=False,
        help_text="Use as a field tag when uploading to Influx",
    )

    class Meta:
        ordering = ["order"]
        verbose_name = "Message Item"

    def __str__(self):
        return f"{self.msgID.msgName}: {self.name}"


class HtmlTemplate(models.Model):
    """
    This model is used to list available templates
    """

    templateName = models.CharField(max_length=50, blank=True, null=True)
    fileName = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.templateName


class Node(models.Model):
    """
    Model definition for the Node object.

    Functions:
        passOnData - send info about associated nodes/gateways
        msgReceived - updates the node when a new message arrives
        jsonLoad(input) - processes JSON input
        incrementMsgCnt - increments message count for node
    """

    nodeID = models.CharField(max_length=30)
    lastseen = models.DateTimeField(blank=True, null=True)
    cameOnline = models.DateTimeField(blank=True, null=True)
    upTime = models.FloatField("Uptime in minutes", default=0.0)
    # uptime = models.FloatField(default=0)

    bootTime = models.DateTimeField(blank=True, null=True)
    onlineTime = models.FloatField("Online in minutes", default=0.0)
    status_sent = models.DateTimeField(null=True, blank=True)
    notification_sent = models.BooleanField(default=False)
    lastStatusTime = models.DateTimeField(blank=True, null=True)
    lastDataTime = models.DateTimeField(blank=True, null=True)

    isGateway = models.BooleanField(blank=True, default=False)
    isRepeater = models.BooleanField(blank=True, default=False)

    status = models.CharField(
        max_length=1,
        default=" ",
        help_text="C is current, X is down, M in maintenance mode",
    )
    textStatus = models.CharField(max_length=10, blank=True, null=True)
    topic = models.CharField(max_length=50, blank=True, null=True)
    descr = models.TextField(blank=True, null=True, help_text="")
    lastData = models.TextField(blank=True, null=True)
    lastJSON = models.TextField(blank=True, null=True)
    lastStatus = models.TextField(blank=True, null=True)
    allowedDowntime = models.IntegerField(
        default=60,
        help_text="Minutes that the node can be 'unheard' before being marked as Offline",
    )
    hardware = models.CharField(max_length=50, blank=True, null=True)
    software = models.CharField(max_length=50, blank=True, null=True)
    production = models.BooleanField(
        "Production node",
        default=False,
        help_text="If selected, node will be treated as production, not test",
    )
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    battName = models.CharField(
        max_length=40,
        blank=True,
        null=True,
        default="VBat",
        help_text="The attribute name in JSON messages used for battery levels",
    )
    battMonitor = models.BooleanField(default=False)
    battLevel = models.FloatField(default=0.0)
    battWarn = models.FloatField(
        default=0.0,
        help_text="The battery level, below which warning message are generated",
    )
    battCritical = models.FloatField(
        default=0.0,
        help_text="The battery level, below which critical warning message are generated",
    )
    # dataMsgCount = models.IntegerField(default=0)
    RSSI = models.FloatField(default=0.0)
    team = models.ForeignKey(
        Team, related_name="nodes", on_delete=models.SET_NULL, null=True, blank=True
    )
    portal = models.URLField(
        max_length=100,
        blank=True,
        null=True,
        help_text="A link where more data on this node is available",
    )
    messagetype = models.ForeignKey(
        MessageType,
        blank=True,
        null=True,
        help_text="This message type will be used to convert incoming CSV data to JSON format",
        on_delete=models.SET_NULL,
    )
    influxUpload = models.BooleanField(
        "Upload to InfluxDB",
        default=False,
        help_text="Select this if you want data uploaded to InfluxDB.",
    )
    thingsboardUpload = models.BooleanField(
        "Upload to Thingsboard",
        default=False,
        help_text="Select this if you want data uploaded to Thingsboard on AWS2. NB Thingsboard cred also needs to be completed.",
    )
    locationOverride = models.BooleanField(
        "Location override",
        default=False,
        help_text="If selected, incoming location data will be ignored and stored data passed on",
    )
    projectOverride = models.BooleanField(
        "Project override",
        default=False,
        help_text="If selected, any incoming Project name will be ignored and stored Project passed on",
    )
    thingsboardCred = models.CharField(
        "Thingsboard credentials",
        max_length=40,
        blank=True,
        null=True,
        help_text="The credentials needed for thingsboard data load",
    )
    trapNZ = models.BooleanField(
        "Upload to TRAP.NZ API",
        default=False,
        help_text="Select this if you want data uploaded to TRAP.NZ.",
    )
    sms_template = models.ForeignKey(
        HtmlTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="smsTemplate",
        help_text="Optional HTML template to be used for SMS node down messages",
    )
    email_down_template = models.ForeignKey(
        HtmlTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="emailDownTemplate",
        help_text="Optional HTML template to be used for email node down messages",
    )
    email_up_template = models.ForeignKey(
        HtmlTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="emailUpTemplate",
        help_text="Optional HTML template to be used for email node up messages",
    )
    email_reminder_template = models.ForeignKey(
        HtmlTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="emailReminderTemplate",
        help_text="Optional HTML template to be used for daily email node down reminder messages",
    )
    email_status_template = models.ForeignKey(
        HtmlTemplate,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="emailStatusTemplate",
        help_text="Optional HTML template to be used for weekly email status messages",
    )
    trapID = models.CharField(
        max_length=30,
        blank=True,
        null=True,
        help_text="The trap ID associated with the sensor",
    )

    class Meta:
        ordering = ["nodeID"]

    def __str__(self):
        return self.nodeID

    def passOnData(self):
        """
        This function returns data about items that have processed data.

        Gateways, returns the nodes they have processed data for,
        Nodes, returns the gateways that have processed their data

        Only data processed in the last 7 data is considered. 

        """
        if self.isGateway:
            passAll = NodeGateway.objects.filter(gatewayID=self).order_by("-lastdata")
        else:  # must be a node
            passAll = NodeGateway.objects.filter(nodeID=self).order_by("-lastdata")
        # Now filter the result so we only get the last 7 days
        passAll = passAll.filter(
            lastdata__gte=(
                timezone.make_aware(
                    datetime.datetime.now(), timezone.get_current_timezone()
                )
                - datetime.timedelta(days=7)
            )
        )
        return passAll

    def msgReceived(self, mqttClient, emailFrom, eMail_topic):
        """
        This function updates node data when a new message is received.
        """
        self.lastseen = timezone.now()

aklc/monitor/forms.py
from django import forms
from .models import Node, MessageType, MessageItem, Team, NodeUser


class ContactForm(forms.Form):
    descr = forms.CharField(widget=forms.Textarea)


class NodeDetailForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = [
            "descr",
            "allowedDowntime",
            "hardware",
            "software",
            "battName",
            "battWarn",
            "battCritical",
            "portal",
            "team",
            "production",
            "latitude",
            "longitude",
            "email_down_template",
            "email_up_template",
            "email_reminder_template",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class NodeNotifyForm(forms.Form):
    NOTIFY_ME = [
        ("Y", "Notify me"),
        ("N", "No notifications, thanks"),
    ]
    email = forms.BooleanField(required=False)
    sms = forms.BooleanField(required=False)
    pushbullet = forms.BooleanField(required=False)
    notification = forms.ChoiceField(choices=NOTIFY_ME)


class MessageTypeDetailForm(forms.ModelForm):
    class Meta:
        model = MessageType
        fields = ["msgName", "descr"]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 1}),
        }


class MessageItemDetailForm(forms.ModelForm):
    class Meta:
        model = MessageItem
        fields = [
            "order",
            "name",
            "isTag",
            "fieldType",
        ]
        widgets = {
            "fieldType": forms.TextInput(attrs={"size": 1}),
        }


class NodeMessageForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = [
            "messagetype",
            "thingsboardUpload",
            "thingsboardCred",
            "influxUpload",
            "trapNZ",
            "locationOverride",
            "projectOverride",
        ]
        # widgets = {
        #    'thingsboardCred': forms.Textarea(attrs={'rows': 3}),
        # }


class ProjectDetailForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "descr",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class ProjectAddForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "teamID",
            "descr",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class UserProfileForm(forms.Form):
    # NOTIFY_ME = [
    #    ("Y", "Notify me"),
    #    ("N", "No notifications, thanks"),
    # ]
    firstName = forms.CharField(required=False, label="First name")
    surName = forms.CharField(required=False, label="Surname")
    email = forms.EmailField(required=False, label="Email address")
    phoneNumber = forms.CharField(required=False, label="Phone number")
    pushbulletApi = forms.CharField(required=False, label="PushBullet API key")
    # notification = forms.ChoiceField(choices=NOTIFY_ME)


class PasswordResetForm(forms.Form):
    original = forms.EmailField()


class NodeUserDetailForm(forms.ModelForm):
    class Meta:
        model = NodeUser
        fields = [
            "user",
            "email",
            "sms",
            "pushbullet",
        ]

aklc/monitor/templates/monitor/index_gw.html
{% extends "monitor/webbase.html" %}

{% block pagerefresh %}<meta http-equiv="refresh" content="30">{% endblock %}

{% block title %}
Gateway list
{% endblock %}

{% block navbar %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
 
  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'monitor:index' %}">Data nodes</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'monitor:index_gw' %}">Gateways</a>
      </li>
      {% if perms.monitor.change_messagetype %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'monitor:index_msg' %}">Message Types</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

{% block web-body %}

  <div id="gateways">
          {% if nodeList %}
          <div class="list-group">
          {% for node in nodeList%}
            {% if node.isGateway %}  {% if not node.status == 'M' %}
              {% if node.status == 'X' %}
                <a href="{% url 'monitor:gatewayDetail' node.id %}" class="list-group-item list-group-item-action list-group-item-dark">{{node.nodeID}} (gateway not reporting in)</a>
              {% else %}
                {% if node.descr %}
                  <a href="{% url 'monitor:gatewayDetail' node.id %}" class="list-group-item list-group-item-action list-group-item-success">{{node.nodeID}} ({{node.descr}})</a>
                {% else %}
                  <a href="{% url 'monitor:gatewayDetail' node.id %}" class="list-group-item list-group-item-action list-group-item-success">{{node.nodeID}}</a>
                {% endif %}
              {% endif %}
            {% endif %} {% endif %}
          {% endfor %}
          </div>
        {% else %}
          <p>No gateways defined</p>>
        {% endif %} 
      </div>
    

{% endblock %}

aklc/monitor/templates/monitor/mqtt-nodemaintenance.html
{% extends "base.html" %}

{% block title %}
MQTT Request
{% endblock %}

{% block email-body %}
  <p>Hi {{ name }}</p>

  <p>sys-monitor received a request to put this node into maintenance mode</p>
  <p> {{ request }}</p>
  <p> {{ result }}</p>
  <p>Node name: {{ node.nodeID }}</p>
  <p>Next update will be after: {{ node.next_update }}</p>

  <table>
    <tr>
      <td>Node ID:</td><td>{{ node.nodeID }}</td>
    </tr>
    <tr>
      <td>Next update will be after:</td><td>{{ node.next_update }}</td>
    </tr>

  </table>
{% endblock %}

aklc/monitor/templates/monitor/msgDetail.html
{% extends "monitor/webbase.html" %}

{% block title %}
Node Details
{% endblock %}

{% block web-body %}
<div class="iot_background">

  <div id="node-header"><H2>Node information</H2></div>
    <div id="node_detail" class="content_block">
      <div id="node_det_table">
        <table>
          <tr><th>Message Name: </th><th>{{ msg.msgName }}</th></tr>
          <tr><td>Description: </td><td class = "wrap_cell">{{ msg.descr }}</td></tr>
          <tr><td>Data items: </td></tr>
          <tr><th>Order</th><th>Name</th><th>Field type</th><th>Influx tag</th></tr>
          {% for item in msgItems %}
            <tr><td>{{ item.order }}</td><td>{{ item.name }}</td><td>{{ item.fieldType }}</td><td>{{ item.isTag }}</td></tr>
          {% endfor %}
        </table>
      </div>
      <div id="node_det_button" class="action_button">
        <a href="{% url 'monitor:msgUpdate' msg.id %}" class="btn btn-info" role="button">Update details</a>
      </div>
      <div id="message_usage_table">
        <h3>Nodes using this message</h3>
        <table>
          <tr><th>Node</th></tr>
          {% for node in msgNodes %} 
            <tr><td><a href="{% url 'monitor:nodeDetail' node.id %}">{{node.nodeID}}</a></td></tr>
          {% endfor %}
        </table>
      </div>      
    </div>
  </div>

  <a href="{% url 'monitor:index_msg' %}" class="btn btn-info" role="button">Home</a>
</div>
{% endblock %}

aklc/monitor/templates/monitor/msgUpdate.html
{% extends "monitor/webbase.html" %}

{% block title %}
Message type update
{% endblock %}

{% block web-body %}
<div class="iot_background">
  <div id="node-header"><h3>Update Node information</h3></div>
    <div id="node_detail" class="content_block">
      <div id="node_det_table">
        <form action="{% url 'monitor:msgUpdate' msg.id %}" method="POST">
          {% csrf_token %}
          {{ fItems.management_form }}
          {{ form.non_field_errors}}
          <table>
            {{ form.as_table }}

            <tr><th>Order</th><th>Name</th><th>Type of Data</th><th>Influx tag</th><th>Delete</th></tr>

            {% for itm in fItems %}
              <tr><td>{{ itm.order }}</td><td>{{ itm.name }}</td><td>{{ itm.fieldType }}</td><td>{{ itm.isTag }}</td><td>{{ itm.DELETE }}</td><td>{{ itm.id }}</td><td>{{ itm.errors }}</td></tr>
            {% endfor %}

          </table>
        <input type="submit" value="Submit">
        <span id="node_cancel_button" class="cancel_button">
          <a href="{% url 'monitor:msgDetail' msg.id %}" class="btn btn-link btn-outline-warning" role="button">Cancel</a>
        </span>
      </form>
    </div>
  </div>
 
</div>
{% endblock %}

aklc/monitor/templates/monitor/nodeUpdate.html
{% extends "monitor/webbase.html" %}

{% block title %}
Node Details
{% endblock %}

{% block web-body %}
<div class="iot_background">
  <div id="node-header"><h3>Update Node information for {{ node.nodeID }}</h3></div>
    <div id="node_detail" class="content_block">
      <div id="node_det_table">
        <form action="{% url 'monitor:nodeUpdate'  node.id %}" method="POST">
          {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
        <input type="submit" value="Submit">
        <span id="node_cancel_button" class="cancel_button">
          <a href="{% url 'monitor:nodeDetail' node.id %}" class="btn btn-link btn-outline-warning" role="button">Cancel</a>
        </span>
      </form>
    </div>
  </div>
 
</div>
{% endblock %}

aklc/monitor/templates/monitor/projectAdd.html
{% extends "monitor/webbase.html" %}

{% block title %}
Add a Project
{% endblock %}

{% block web-body %}
<div class="iot_background">
  <div id="node-header"><h3>Add a project</h3></div>
    <div id="node_detail" class="content_block">
      <div id="node_det_table">
        <form action="{% url 'monitor:projectAdd' %}" method="POST">
          {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
        <input type="submit" value="Submit">
        <span id="node_cancel_button" class="cancel_button">
          <a href="{% url 'monitor:index_prj' %}" class="btn btn-link btn-outline-warning" role="button">Cancel</a>
        </span>
      </form>
    </div>
  </div>
 
</div>
{% endblock %}

aklc/monitor/templates/monitor/projectUpdate.html
{% extends "monitor/webbase.html" %}

{% block title %}
Project Details
{% endblock %}

{% block web-body %}
<div class="iot_background">
  <div id="node-header"><h3>Update Project information for {{ prj.teamID }}</h3></div>
    <div id="node_detail" class="content_block">
      <div id="node_det_table">
        <form action="{% url 'monitor:projectUpdate'  prj.id %}" method="POST">
          {% csrf_token %}
          <table>
            {{ form.as_table }}
          </table>
        <input type="submit" value="Submit">
        <span id="node_cancel_button" class="cancel_button">
          <a href="{% url 'monitor:projectDetail' prj.id %}" class="btn btn-link btn-outline-warning" role="button">Cancel</a>
        </span>
      </form>
    </div>
  </div>
 
</div>
{% endblock %}

aklc/monitor/templates/monitor/webbase-w3css.html
{% load static %}
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link rel="stylesheet" href="{% static "monitor/style.css" %}">    
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css"> 
    {% block pagerefresh %}<meta http-equiv="refresh" content="600">{% endblock %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132422735-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-132422735-2');
    </script>

    <title>
	    {% block title %}
        Node monitoring system
      {% endblock %}
    </title>
  </head>
  <body class="iot_background">
    {% block background %}
      <div class="w3-container">
    {% endblock %}
    
      <div id="logged_in">
        {% if user.is_authenticated %}
          Hi <a href="{% url 'monitor:userProfile' %}">{{ user.username|capfirst }} <a href="{% url 'monitor:logout' %}">Logout</a>
        {% else %}
          Not logged in 
        {% endif %}
      </div>
      <div id="pg_header">
        <img src="{% static 'monitor/LOGO.png' %}" class = "logo">
        <span class="heading_text">Innovate Auckland Monitoring {{ dev_msg }}</span>
      </div>

      {% block navbar %}
      <nav class="w3-bar w3-dark-grey">
       
            {% if nodeactive %}
              <a class="w3-bar-item w3-button w3-black w3-mobile" href="{% url 'monitor:index' %}">Data nodes</a>
            {% else %}
              <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:index' %}">Data nodes</a>
            {% endif %}

            {% if repeateractive %}
              <a class="w3-bar-item w3-button w3-black w3-mobile" href="{% url 'monitor:index_rp' %}">Repeaters</a>
            {% else %}
              <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:index_rp' %}">Repeaters</a>
            {% endif %}
            
            {% if gatewayactive %}
              <a class="w3-bar-item w3-button w3-black w3-mobile" href="{% url 'monitor:index_gw' %}">Gateways</a>
            {% else %}
              <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:index_gw' %}">Gateways</a>
            {% endif %}

            {% if perms.monitor.change_messagetype %}
              {% if msgactive %}
                <a class="w3-bar-item w3-button w3-black w3-mobile" href="{% url 'monitor:index_msg' %}">Message Types</a>
              {% else %}
                <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:index_msg' %}">Message Types</a>
              {% endif %}
            {% endif %}

            {% if perms.monitor.change_team %}
              {% if prjactive %}
                <a class="w3-bar-item w3-button w3-black w3-mobile" href="{% url 'monitor:index_prj' %}">Projects</a>
              {% else %}
                <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:index_prj' %}">Projects</a>
              {% endif %}
            {% endif %}

            <a class="w3-bar-item w3-button w3-mobile" href="{% url 'monitor:DashboardStatus' %}">Dashboard status</a>

            <a class="w3-bar-item w3-button w3-right w3-mobile" href="{% url 'monitor:about' %}">About</a>
            <a class="w3-bar-item w3-button w3-right w3-mobile" href="{% url 'monitor:contact' %}">Contact</a>

      </nav>
      {% endblock %}

      {% block web-body %}
        Node monitor
      {% endblock %}
      <!-- START FOOTER -->
      <div class="footer w3-container">
        <span class="">Auckland Council Innovation team</span>
      </div>
      <!-- END FOOTER -->
    </div>

  </body>
</html>