aklc/aklc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('monitor.urls')),
    path('admin/', admin.site.urls),
    path('monitor/', include('monitor.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
]

aklc/monitor/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views, accounts, apiviews

app_name = "monitor"
urlpatterns = [
    path("", views.index, name="index"),
    path("index_gw/", views.index_gw, name="index_gw"),
    path("node/<int:node_ref>/", views.nodeDetail, name="nodeDetail"),
    path("gateway/<int:gateway_ref>/", views.gatewayDetail, name="gatewayDetail"),
    path("node/update/<int:node_ref>/", views.nodeUpdate, name="nodeUpdate"),
    path("node/modupdate/<int:node_ref>/", views.nodeModNotify, name="nodeModNotify"),
    path(
        "node/modupdateothers/<int:node_ref>/",
        views.nodeModNotifyOthers,
        name="nodeModNotifyOthers",
    ),
    path("node/remove/<int:node_ref>/", views.nodeRemove, name="nodeRemove"),
    path(
        "node/mqttlog/<int:node_ref>/<int:mq_ref>/",
        views.nodeMqttLog,
        name="nodeMqttLog",
    ),
    path(
        "gateway/mqttlog/<int:gateway_ref>/<int:mq_ref>/",
        views.gatewayMqttLog,
        name="gatewayMqttLog",
    ),
    path("node/tb1/<int:node_ref>/", views.tb1, name="tb1"),
    path("node/tb2/<int:node_ref>/", views.tb2, name="tb2"),
    path("index_msg/", views.index_msg, name="index_msg"),
    path("message/<int:msg_ref>/", views.msgDetail, name="msgDetail"),
    path("message/add/", views.msgAdd, name="msgAdd"),
    path("message/update/<int:msg_ref>/", views.msgUpdate, name="msgUpdate"),
    path("node/msgupdate/<int:node_ref>/", views.nodeMsgUpdate, name="nodeMsgUpdate"),
    path("index_prj/", views.index_prj, name="index_prj"),
    path("project/<int:prj_ref>/", views.projectDetail, name="projectDetail"),
    path("project/update/<int:prj_ref>/", views.projectUpdate, name="projectUpdate"),
    path("project/add/", views.projectAdd, name="projectAdd"),
    path("NetworkStatus/", views.dashBoard, name="DashboardStatus"),
    path("index_rp/", views.index_rp, name="index_rp"),
    path("repeater/<int:rp_ref>/", views.repeaterDetail, name="repeaterDetail"),
    path("repeater/update/<int:rp_ref>/", views.repeaterUpdate, name="repeaterUpdate"),
    path("login/", views.login, name="login"),
    path("logout/", accounts.logout, name="logout"),
    path("userprofile/", views.userProfile, name="userProfile"),
    path("userupdate/", views.userUpdate, name="userUpdate"),
    path(
        "password-change/",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/password_change.html",
            success_url="password-change-done",
        ),
        name="passwordChange",
    ),
    path(
        "password-change/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_change_done.html",
        ),
        name="passwordChangeDone",
    ),
    path("password-reset/", views.passwordReset, name="password-reset"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),

    # paths for API's
    path("api/teams/", apiviews.team_list, name="api-team-list"),
    path("api/teamdetail/<int:team_ref>/", apiviews.api_team_view, name="api-team-view"),
    path("api/nodedetail/<int:node_ref>/", apiviews.api_node_view, name="api-node-view"),
    path("api/messagelist/", apiviews.message_list, name="api-message-list"),
    path("api/messagedetail/<int:msgtype_ref>/", apiviews.message_detail, name="api-message-detail"),
]

aklc/monitor/forms.py
from django import forms
from .models import Node, MessageType, MessageItem, Team, NodeUser


class ContactForm(forms.Form):
    descr = forms.CharField(widget=forms.Textarea)


class NodeDetailForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = [
            "descr",
            "allowedDowntime",
            "hardware",
            "software",
            "battName",
            "battWarn",
            "battCritical",
            "portal",
            "team",
            "production",
            "latitude",
            "longitude",
            "email_down_template",
            "email_up_template",
            "email_reminder_template",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class NodeNotifyForm(forms.Form):
    NOTIFY_ME = [
        ("Y", "Notify me"),
        ("N", "No notifications, thanks"),
    ]
    email = forms.BooleanField(required=False)
    sms = forms.BooleanField(required=False)
    pushbullet = forms.BooleanField(required=False)
    notification = forms.ChoiceField(choices=NOTIFY_ME)


class MessageTypeDetailForm(forms.ModelForm):
    class Meta:
        model = MessageType
        fields = ["msgName", "descr"]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 1}),
        }


class MessageItemDetailForm(forms.ModelForm):
    class Meta:
        model = MessageItem
        fields = [
            "order",
            "name",
            "isTag",
            "fieldType",
        ]
        widgets = {
            "fieldType": forms.TextInput(attrs={"size": 1}),
        }


class NodeMessageForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = [
            "messagetype",
            "thingsboardUpload",
            "thingsboardCred",
            "influxUpload",
            "trapNZ",
            "locationOverride",
            "projectOverride",
        ]
        # widgets = {
        #    'thingsboardCred': forms.Textarea(attrs={'rows': 3}),
        # }


class ProjectDetailForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "descr",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class ProjectAddForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = [
            "teamID",
            "descr",
        ]
        widgets = {
            "descr": forms.Textarea(attrs={"rows": 3}),
        }


class UserProfileForm(forms.Form):
    # NOTIFY_ME = [
    #    ("Y", "Notify me"),
    #    ("N", "No notifications, thanks"),
    # ]
    firstName = forms.CharField(required=False, label="First name")
    surName = forms.CharField(required=False, label="Surname")
    email = forms.EmailField(required=False, label="Email address")
    phoneNumber = forms.CharField(required=False, label="Phone number")
    pushbulletApi = forms.CharField(required=False, label="PushBullet API key")
    # notification = forms.ChoiceField(choices=NOTIFY_ME)


class PasswordResetForm(forms.Form):
    original = forms.EmailField()


class NodeUserDetailForm(forms.ModelForm):
    class Meta:
        model = NodeUser
        fields = [
            "user",
            "email",
            "sms",
            "pushbullet",
        ]

aklc/monitor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import auth, messages
from django.urls import reverse
from django.utils import timezone
import datetime, os

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .models import (
    Node,
    NodeUser,
    MessageType,
    MessageItem,
    Team,
    MqttQueue,
    MqttStore,
    notificationLog,
    webNotification,
)

from .forms import (
    NodeDetailForm,
    NodeNotifyForm,
    MessageTypeDetailForm,
    MessageItemDetailForm,
    NodeMessageForm,
    ProjectDetailForm,
    ProjectAddForm,
    UserProfileForm,
    PasswordResetForm,
    NodeUserDetailForm,
)

from .serializers import TeamSerializer

from django.forms import modelformset_factory
from django.contrib.auth.forms import PasswordChangeForm

from .support import sendNotification

testFlag = os.getenv("AKLC_TESTING", False)


def index(request):
    """
    View that displays all current nodes.
    """
    dMonthAgo = timezone.make_aware(
        datetime.datetime.now(), timezone.get_current_timezone()
    ) - datetime.timedelta(days=31)
    # get all the nodes
    nodeList = (
        Node.objects.order_by("nodeID")
        .exclude(status="M")
        .exclude(lastseen__lte=dMonthAgo)
    )
    # remove any Gateways
    nodeList = nodeList.exclude(isGateway=True)

    nodeByTeam = (
        Node.objects.order_by("team", "nodeID")
        .exclude(status="M")
        .exclude(lastseen__lte=dMonthAgo)
    )
    nodeByTeam = nodeByTeam.exclude(isGateway=True).exclude(isRepeater=True)

    noTeamNode = nodeByTeam.exclude(team__isnull=False)

    nodeBlock = []
    if len(nodeByTeam) != len(noTeamNode):
        teamDict = {"Name": nodeByTeam[0].team.teamID, "teamBlock": []}
        tTeam = nodeByTeam[0].team

        # teamBlock = []
        innerBlock = []
        nCnt = 0

        for n in nodeByTeam:

            if n.team != tTeam:  # change teams
                # print(f"Team change, now {n.team}")
                teamDict["teamBlock"].append(innerBlock)
                nodeBlock.append(teamDict)
                if not n.team:
                    # print(f"Break at {n.nodeID}")
                    break

                # set up for next team
                teamDict = {"Name": n.team.teamID, "teamBlock": []}
                tTeam = n.team
                nCnt = 0
                innerBlock = []
                teamBlock = []

            if nCnt > 5:
                nCnt = 0
                teamDict["teamBlock"].append(innerBlock)
                innerBlock = []

            innerBlock.append(n)
            nCnt += 1
        else:
            teamDict = {}
    # Now do those with no team assigned
    teamDict = {"Name": "No project", "teamBlock": []}
    # print("Process no team")
    innerBlock = []
    nCnt = 0
    # teamBlock = []
    for n in nodeByTeam:
        if not n.team:
            # print(n.nodeID)
            innerBlock.append(n)
            nCnt += 1
        if nCnt > 5:
            nCnt = 0
            teamDict["teamBlock"].append(innerBlock)
            innerBlock = []
    if len(innerBlock) > 0:
        teamDict["teamBlock"].append(innerBlock)
    nodeBlock.append(teamDict)

    # print(nodeBlock)

    context = {"nodeList": nodeList, "nodeactive": "Y", "nodeBlock": nodeBlock}
    if os.getenv("AKLC_TESTING", False):
        context["dev_msg"] = "(Development)"
    # context = {"nodeList": nodeList, "nodeactive": "Y"}
    if request.user.groups.filter(name="BetaTesters").exists():
        return render(request, "monitor/index2.html", context)
    else:
        return render(request, "monitor/index2.html", context)


def index_gw(request):
    """
    View for Gateways.
    """
    dMonthAgo = timezone.make_aware(
        datetime.datetime.now(), timezone.get_current_timezone()
    ) - datetime.timedelta(days=31)
    nodeList = (
        Node.objects.order_by("nodeID")
        .exclude(status="M")
        .exclude(lastseen__lte=dMonthAgo)
    )
    # Remove anything that is not a gateway
    nodeList = nodeList.exclude(isGateway=False)
    gw_block = []  # will be a list of lists
    nCnt = 1
    innerList = []
    for g in nodeList:  # cycle through the gateways
        innerList.append(g)
        nCnt += 1
        if nCnt > 6:
            gw_block.append(innerList)
            nCnt = 1
            innerList = []

    if len(innerList) > 0:
        gw_block.append(innerList)

    context = {"nodeList": nodeList, "gatewayactive": "Y", "gw_block": gw_block}
    if os.getenv("AKLC_TESTING", False):
        context["dev_msg"] = "(Development)"

    if request.user.groups.filter(name="BetaTesters").exists():
        return render(request, "monitor/index_gw2.html", context)
    else:
        return render(request, "monitor/index_gw2.html", context)


def index_rp(request):
    """
    View for repeaters.
    """
    dMonthAgo = timezone.make_aware(
        datetime.datetime.now(), timezone.get_current_timezone()
    ) - datetime.timedelta(days=31)
    nodeList = (
        Node.objects.order_by("nodeID")
        .exclude(status="M")
        .exclude(lastseen__lte=dMonthAgo)
    )
    # Remove anything that is not a repeater
    nodeList = nodeList.exclude(isRepeater=False)

    rp_block = []  # will be a list of lists
    nCnt = 1
    innerList = []
    for g in nodeList:  # cycle through the gateways
        innerList.append(g)
        nCnt += 1
        if nCnt > 6:
            rp_block.append(innerList)
            nCnt = 1
            innerList = []

    if len(innerList) > 0:
        rp_block.append(innerList)

    context = {"repeaterList": rp_block, "repeateractive": "Y"}
    if os.getenv("AKLC_TESTING", False):
        context["dev_msg"] = "(Development)"

    return render(request, "monitor/index_rp.html", context)


# @login_required
@permission_required("monitor.view_messagetype")
def index_msg(request):
    """
    View for message types.
    """
    msgList = MessageType.objects.order_by("msgName")
    context = {"msgList": msgList, "msgactive": "Y"}
    if testFlag:
        context["dev_msg"] = "(Development)"

    return render(request, "monitor/index_msg.html", context)


@login_required
def index_prj(request):
    """
    View for projects.
    """
    prjList = Team.objects.order_by("teamID")
    context = {"prjList": prjList, "prjactive": "Y"}
    if testFlag:
        context["dev_msg"] = "(Development)"
    return render(request, "monitor/index_prj.html", context)


@login_required
def nodeDetail(request, node_ref):
    """
    View to display details of a node
    """
    node = get_object_or_404(Node, pk=node_ref)
    passList = node.passOnData()  # gateways that have processed msg from this node
    aNodeUsers = NodeUser.objects.filter(
        nodeID=node
    )  # users that have an 'interest' in this node
    nLog = notificationLog.objects.filter(node=node)[:50]
    context = {
        "node": node,
        "user": request.user,
        "aNodeUser": aNodeUsers,
        "passData": passList,
        "nodeactive": "Y",
        "nLog": nLog,
    }
    if request.user.is_staff:
        context["staff"] = "Y"
    if testFlag:
        context["dev_msg"] = "(Development)"
    return render(request, "monitor/nodeDetail.html", context)


@login_required
def gatewayDetail(request, gateway_ref):
    """
    View to display Gateway details
    """
    gw = get_object_or_404(Node, pk=gateway_ref)
    aNodeUsers = NodeUser.objects.filter(
        nodeID=gw
    )  # users that have an 'interest' in this gateway
    passList = gw.passOnData()  # nodes that have been processed by this gateway
    nLog = notificationLog.objects.filter(node=gw)[:50]
    context = {
        "gateway": gw,
        "user": request.user,
        "aNodeUser": aNodeUsers,
        "passData": passList,
        "gatewayactive": "Y",
        "nLog": nLog,
    }
    if testFlag:
        context["dev_msg"] = "(Development)"
    return render(request, "monitor/gatewayDetail.html", context)


@login_required
def repeaterDetail(request, rp_ref):
    """
    View to display Repeater details
    """
    rp = get_object_or_404(Node, pk=rp_ref)
    aNodeUsers = NodeUser.objects.filter(
        nodeID=rp
    )  # users that have an 'interest' in this gateway
    passList = rp.passOnData()  # nodes that have been processed by this repeater
    nLog = notificationLog.objects.filter(node=rp)[:50]
    context = {
        "node": rp,
        "user": request.user,
        "aNodeUser": aNodeUsers,
        "passData": passList,
        "repeateractive": "Y",
        "nLog": nLog,
    }
    if testFlag:
        context["dev_msg"] = "(Development)"
    return render(request, "monitor/repeaterDetail.html", context)


@login_required
def nodeUpdate(request, node_ref):
    """
    View to process info update form from nodes or gateways
    """
    node = get_object_or_404(Node, pk=node_ref)
    if request.method == "POST":

        nf = NodeDetailForm(
            request.POST, instance=node
        )  # NodeDetailForm defines in forms.py
        if nf.is_valid():
            nf.save()
            return HttpResponseRedirect(reverse("monitor:nodeDetail", args=[node.id]))
        else:
            print("Invalid form")
    # if a GET (or any other method) we'll create a blank form
    else:
        nf = NodeDetailForm(instance=node)
    context = {"form": nf, "node": node}

    if node.isGateway:
        context["gatewayactive"] = "Y"
    elif node.isRepeater:
        context["repeateractive"] = "Y"
    else:
        context["nodeactive"] = "Y"
    if testFlag:
        context["dev_msg"] = "(Development)"
    return render(request, "monitor/nodeUpdate.html", context)


@login_required

aklc/monitor/templates/accounts/login.html
{% extends "monitor/webbase.html" %}

{% block title %}
    Login - {{ block.super }}
{% endblock %}

{% block web-body %}
HELP
    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">

            <h4>Login</h4>
            <hr>

            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-info">{{ message }}</p>
                {% endfor %}
            {% endif %}            
            <form method="post">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <th><label for="id_username">Username:</label></th>
                        <td><input type="text" name="username" id="id_username" required /></td>
                    </tr>
                    <tr>
                        <th><label for="id_password">Password:</label></th>
                        <td><input type="password" name="password" id="id_password" required /></td>
                    </tr>
                    <tr>
                        <td><input type="hidden" name="next" value=""></td>
                        <td><button type="submit" class="btn btn-primary">Submit</button></td>
                    </tr>
                </table>
            </form>            
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">

            <h4>Related Links</h4>
            <p>
                <a href="{% url 'monitor:password-reset' %}">Forgot Password?</a> <br>
                                                      
{% comment %}
                <a href="{% url 'monitor:signup' %}">Sign Up</a> <br>
                <a href="/contact/">Feedback</a>
{% endcomment %}
            </p>
            
        </div>
    </div>

{% endblock %}

aklc/monitor/templates/accounts/logout.html
{% extends "monitor/webbase.html" %}

{% block title %}
    Logout - {{ block.super }}
{% endblock %}

{% block web-body %}

    <div class="container">

        <p>You are logged out. <a href="{% url 'monitor:login' %}">Click here</a> to login again.</p>

    </div>

{% endblock %}

aklc/monitor/templates/accounts/password_change.html
{% extends "monitor/webbase.html" %}

{% block title %}
    Password Change - {{ block.super }}
{% endblock %}

{% block web-body %}

    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Password Change</h4>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-info">{{ message }}</p>
                {% endfor %}
            {% endif %}

            <form method="post">

                {% csrf_token %}

                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td><input type="hidden" name="next" value="{{ next }}"></td>
                        <td><button type="submit" class="btn btn-primary">Submit</button></td>
                    </tr>
                </table>

            </form>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
{% comment %}                <a href="{% url 'monitor:signup' %}">Sign Up</a> <br> {% endcomment %}
                <a href="{% url 'monitor:login' %}">Login.</a> <br>
            </p>
        </div>

    </div>

{% endblock %}

aklc/monitor/templates/accounts/password_change_done.html
{% extends "monitor/webbase.html" %}

{% block title %}
    Password Change Done- {{ block.super }}
{% endblock %}

{% block web-body %}
<div class="iot_background">
  <p>Your password was changed.</p>
</div>
{% endblock %}

aklc/monitor/templates/accounts/password_reset.html
{% extends "monitor/webbase.html" %}

{% block title %}
    Password Reset - {{ block.super }}
{% endblock %}

{% block web-body %}

    <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Password Reset</h4>
            <hr>
            {% if messages %}
                {% for message in messages %}
                    <p class="alert alert-info">{{ message }}</p>
                {% endfor %}
            {% endif %}

            <form method="post">

                {% csrf_token %}

                <table class="table">
                    {{ form.as_table }}
                    <tr>
                        <td><input type="hidden" name="next" value="{{ next }}"></td>
                        <td><button type="submit" class="btn btn-primary">Submit</button></td>
                    </tr>
                </table>

            </form>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                <a href="{% url 'beedb:signup' %}">Sign Up</a> <br>
                <a href="{% url 'beedb:login' %}">Login.</a> <br>
            </p>
        </div>

    </div>

{% endblock %}

aklc/monitor/templates/accounts/password_reset_complete.html
{% extends "monitor/webbase.html" %}

{% load static %}
{% load humanize %}

{% block web-body %}

    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">

            <h4>Password Reset Success</h4>

            <hr>

            <div class="db-form">

                <p>Your password has been reset. Click <a href="{% url 'monitor:login' %}">Login</a>
            
            </div>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                 <a href="{% url 'monitor:password_reset' %}">Forgot Password?</a> <br>
{% comment %}                <a href="{% url 'monitor:signup' %}">Sign Up</a> <br> {% endcomment %}
                <a href="#">Feedback</a>
            </p>
        </div>

    </div>

{% endblock %}

aklc/monitor/templates/accounts/password_reset_confirm.html
{% extends "monitor/webbase.html" %}

{% load static %}
{% load humanize %}

{% block web-body %}

    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">

            <h4>Enter your new password.</h4>
            <hr>
            {% if validlink %} 
 {% comment %}               <form action="{% url 'beedb:password_reset_complete' %}" method="post"> {% endcomment %}
                    <form action="" method="post">
                    <table>
                        {% csrf_token %}
                        {{ form.as_table }}
                        <tr>
                            <td></td>
                            <td><button type="submit" class="btn btn-primary">Reset Password</button></td>
                        </tr>
                    </table>
                </form>
            {% else %}
                <p>This Link is no longer valid. Click <a href="{% url 'beedb:password_reset' %}">here</a> to create a new one.</p>
            {% endif %}

        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                <a href="{% url 'beedb:password_reset' %}">Forgot Password?</a> <br>
                <a href="{% url 'beedb:signup' %}">Sign Up.</a> <br>
                <a href="#">Feedback</a>
            </p>
        </div>

    </div>

{% endblock %}

aklc/monitor/templates/accounts/password_reset_done.html
{% extends "monitor/webbase.html" %}

{% load static %}
{% load humanize %}

{% block web-body %}

    <div class="row">

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Email Sent</h4>
            <hr>
            <p>Password reset link has been sent to your email.</p>
        </div>

        <div class="col-lg-6 col-md-6 col-sm-6">
            <h4>Related Links</h4>
            <p>
                <a href="{% url 'beedb:password_reset' %}">Forgot Password?</a> <br>
                <a href="{% url 'beedb:signup' %}">Sign Up.</a> <br>
                <a href="#">Feedback</a>
            </p>
        </div>

    </div>

{% endblock %}